<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Models\User;
use App\Models\Sale;
use App\Models\CommissionPayment;
use App\Models\SystemSetting;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class ProcessCommissionPayments extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'commission:process-payments';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Process automatic commission payments for affiliates';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info('Starting commission payment processing...');

        try {
            DB::beginTransaction();

            // Get all affiliates with pending commissions
            $affiliates = User::affiliates()
                ->active()
                ->whereHas('affiliateSales', function ($query) {
                    $query->confirmed();
                })
                ->get();

            $processedCount = 0;

            foreach ($affiliates as $affiliate) {
                $pendingCommission = $affiliate->pending_commission;

                if ($pendingCommission > 0) {
                    // Check if affiliate meets minimum payout threshold
                    $minPayout = SystemSetting::get('min_commission_payout', 50.00);

                    if ($pendingCommission >= $minPayout) {
                        // Create automatic commission payment
                        $payment = new CommissionPayment([
                            'user_id' => $affiliate->id,
                            'amount' => $pendingCommission,
                            'status' => CommissionPayment::STATUS_PENDING,
                            'payment_method' => CommissionPayment::PAYMENT_PIX,
                            'notes' => 'Automatic commission payment generated by system',
                        ]);

                        $payment->save();
                        $processedCount++;

                        Log::info("Commission payment created for affiliate {$affiliate->name}: R$ {$pendingCommission}");
                    }
                }
            }

            DB::commit();

            $this->info("Commission payment processing completed. {$processedCount} payments created.");
            Log::info("Commission payment processing completed. {$processedCount} payments created.");

        } catch (\Exception $e) {
            DB::rollBack();
            $this->error('Error processing commission payments: ' . $e->getMessage());
            Log::error('Error processing commission payments: ' . $e->getMessage());
            return 1;
        }

        return 0;
    }
}

